apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tcoh34cvw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tcoh34cvw-nodejs 
  name: tcoh34cvw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tcoh34cvw-nodejs 
